set(_CATKIN_CURRENT_PACKAGE "pam")
set(pam_VERSION "0.0.0")
set(pam_MAINTAINER "roya <roya@todo.todo>")
set(pam_PACKAGE_FORMAT "2")
set(pam_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(pam_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(pam_BUILDTOOL_DEPENDS "catkin")
set(pam_BUILDTOOL_EXPORT_DEPENDS )
set(pam_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(pam_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(pam_TEST_DEPENDS )
set(pam_DOC_DEPENDS )
set(pam_DEPRECATED "")